### ISSUE TITLE
Synonym Exploration

### ISSUE THREAD

**Issue by SebZG** [SebZG/lexi-deck#4]
### User Story
As a writer, I want to see synonyms for words, so I can expand my vocabulary and improve my writing.

### Acceptance Criteria
- [x] Display related synonyms for searched words
- [x] Easy-to-read synonym layout
- [x] Ability to click synonyms to search them

### Tasks
- [x] Integrate synonym API functionality
- [x] Design synonym display interface
- [x] Add synonym click-to-search feature
