### ISSUE TITLE
Favorite Words Management

### ISSUE THREAD

**Issue by SebZG** [SebZG/lexi-deck#7]
### User Story
As a learner, I want to save words I'm learning, so I can review them later.

### Acceptance Criteria
- [ ] Ability to mark words as favorites
- [ ] View list of favorite words
- [ ] Remove words from favorites
- [ ] Favorites persist between sessions

### Tasks
- [ ] Add favorite toggle button for words
- [ ] Create favorites storage system
- [ ] Build favorites view interface
- [ ] Implement favorite word removal
